version: "3.7"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  # hiring-exercise:
  #   image: hiring-excerise:dev
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   volumes:
  #     - '.:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 8081:8080

volumes:
  mongodb_data_container: null
