name: Verify Frontend
on:
  pull_request:
    path:
      - frontend/**
jobs:
  Test-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Building Frontend
        run: cd frontend && npm run build
      - name: Test
        run: cd frontend && npm run test
