name: Verify API
on:
  push:
    path:
      - api/**
jobs:
  Test-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running"

name: Verify Frontend
on:
  push:
    path:
      - frontend/**
jobs:
  Test-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running"